spring:
  application:
    name: morning-service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=UTC

eureka:
  #instance:
   # hostname: morning-service-product
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8763
